apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mesh-deployment
spec:
  selector:
    matchLabels:
      app: book-mesh
      version: v1.0
  replicas: 3
  template:
    metadata:
      labels:
        app: book-mesh
        version: v1.0
    spec:
      containers:
      - name: book-mesh
        image: kix.ocir.io/apackrsct01/oci-demo-registry/sample-book-rest:latest
        imagePullPolicy: Always
        ports:
        - name: book-mesh
          containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: book-mesh-service
  labels:
    app: book-mesh
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: book-mesh
