#------------------------------------------------------------------------------
# chapter2/demo-virtualservices.yaml
# 기존 virtualservice를 업데이트
# 유저메시 앱 버전에 따라 v1.1 80%, v1.2 20% 라우팅 정책 적용
#------------------------------------------------------------------------------

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - match:
    - uri:
        prefix: /v1/user
    route:
    - destination:
        host: user-mesh-service
        port:
          number: 5000
  - match:
    - uri:
        prefix: /v1/book
    route:
    - destination:
        host: book-mesh-service
        port:
          number: 5000

